apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s*
build:
  local:
    push: true
  artifacts:
    - image: shapeup404/adminservice
      context: admin-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
          