apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin-container
        image: shapeup404/adminservice
---
apiVersion: v1
kind: Service
metadata: 
  name: admin-srv
spec:
  selector:
    app: admin
  ports: 
    - name: admin
      protocol: TCP
      port: 8002
      targetPort: 8002