apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer
  template:
    metadata:
      labels:
        app: trainer
    spec:
      containers:
      - name: trainer
        image: shapeup404/trainerservice
---
apiVersion: v1
kind: Service
metadata:
  name: trainer-srv
spec:
  selector:
    app: trainer
  ports:
    - name: trainer
      protocol: TCP
      port: 8001
      targetPort: 8001