apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Adjust the value as needed
spec:
  rules:
  - host: aravindreghunath.online
    http:
      paths:
      - path: /api/user/?(.*)
        pathType: Prefix
        backend:
          service:
            name: user-srv
            port:
              number: 8000
      - path: /api/trainer/?(.*)
        pathType: Prefix
        backend:
          service:
            name: trainer-srv
            port:
              number: 8001
      - path: /api/admin/?(.*)
        pathType: Prefix
        backend:
          service:
            name: admin-srv
            port:
              number: 8002
  - host: aravindreghunath.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client-srv
            port:
              number: 5173
  ingressClassName: nginx
